apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c','echo "Testing Empry Dir volume type" > /data/new.txt']
      volumeMounts:
        - name: empty-dir-volume
          mountPath: /data
  volumes:
    - name: empty-dir-volume
      emptyDir: {}
