apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c','cat /data/data.txt']
      volumeMounts:
        - name: ak-host-data
          mountPath: /data
  volumes:
    - name: ak-host-data
      hostPath:
        path: /etc/host-dir
        type: Directory
